name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish app
        run: dotnet publish SeminarHub/SeminarHub.csproj -c Release -o myapp

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: SeminarHub-app
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: myapp
